# Site settings
title: Sam Alfa's Blog
description: A simple Jekyll blog theme fork from Mateus Medeiros 
url: "http://samalfa.github.io/samalfablog/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/samalfablog"

# Author settings
author:
  name     : Sam Alfa
  bio      : I'm interesting about Front End and Back End Developer, I also passionate about new technologies too. I try to learn about new technologies every day.
  email    : sam.tunk@gmail.com
  twitter  :

#SEO settings
logo: /assets/img/img-blog.png/ # Site logo URL
twitter_username: # Twitter username
facebook:
    app_id: #1445035275808959 # App ID
    publisher: https://www.facebook.com/sam.tunk # URL of the Facebook page
    admins: #100000229048939 # Facebook user ID that manages the page

# Build settings
permalink: / :title/
markdown: kramdown
paginate: 5
paginate_path: "/blog/page/:num"

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

css_folder:  "/assets/css"
js_folder:  "/assets/js"
img_folder:  "/assets/img"
sass:
    style: compressed